export const DummyCharacter = [
  {
    id: 1,
    imageUrl: "/character-1.jpg",
    name: "Amara",
    age: 25,
    location: "Atlanta",
    likes: "1.5K",
    chats: "269.1K",
    rating: "2.87k",
    gender: "Female",
    style: "Realistic",
    isV2: true,
    isNew: true,
    isTrending: false,
    description:
      "Atlanta glam with a soft side 💕 Makeup artist & content creator. Lover of gold jewelry, good lighting, and late-night Waffle House runs. Come talk to me. ✨",
  },
  {
    id: 2,
    imageUrl: "/character-2.jpg",
    name: "Sienna",
    age: 22,
    location: "Toronto",
    likes: "744",
    chats: "131.3K",
    rating: "2.87k",
    gender: "Female",
    style: "Realistic",
    isV2: true,
    isNew: true,
    isTrending: true,
    description:
      "Toronto vibes with high energy ✨ Night city skylines & fitness enthusiast. Let's chat about everything. 🌃",
  },
  {
    id: 3,
    imageUrl: "/character-3.jpg",
    name: "Harper",
    age: 26,
    location: "Nashville",
    likes: "1K",
    chats: "269.2K",
    rating: "2.87k",
    gender: "Female",
    style: "Realistic",
    isV2: true,
    isNew: true,
    isTrending: false,
    description:
      "Vintage soul with a love for road trips and classic style. Come say hi! 🚗✨",
  },
  {
    id: 4,
    imageUrl: "/character-4.jpg",
    name: "Paloma",
    age: 23,
    location: "Kingston Ontario",
    likes: "1K",
    chats: "227.7K",
    rating: "2.87k",
    gender: "Female",
    style: "Realistic",
    isV2: true,
    isNew: true,
    isTrending: false,
    description:
      "Sophisticated & chic. Always up for deep conversations and new adventures. 💫",
  },
];

